"""Optional-path Notion publisher. Output-only by design.

Writes one page per weekly report into a scratch Notion database:
pipeline snapshot as a table block, hygiene section as callouts. It never
reads, never syncs, never touches anything resembling a source of record.

Setup (2 lines, see README): create an internal integration, share a scratch
database with it, then:
  export NOTION_TOKEN=secret_...
  export NOTION_DATABASE_ID=...

API shapes verified against the installed notion-client 3.x package source
(notion_client/api_endpoints.py); the bundled notion_docs/ are end-user
guides without API reference.
"""

from __future__ import annotations

import os

from auditor.models import CanonicalPipeline
from auditor.queue import load_queue
from auditor.report import (
    REPORT_STAGES,
    confidence_line,
    hygiene_stats,
    snapshot_counts,
)


def _text(content: str) -> list[dict]:
    return [{"type": "text", "text": {"content": content}}]


def _heading(content: str) -> dict:
    return {"object": "block", "type": "heading_2",
            "heading_2": {"rich_text": _text(content)}}


def _callout(content: str, emoji: str) -> dict:
    return {"object": "block", "type": "callout",
            "callout": {"rich_text": _text(content),
                        "icon": {"type": "emoji", "emoji": emoji}}}


def _table_row(cells: list[str]) -> dict:
    return {"object": "block", "type": "table_row",
            "table_row": {"cells": [_text(c) for c in cells]}}


def snapshot_table_block(pipeline: CanonicalPipeline) -> dict:
    counts = snapshot_counts(pipeline)
    header = ["role"] + [s.value for s in REPORT_STAGES] + ["total"]
    rows = [_table_row(header)]
    for role in sorted(counts):
        cells = [role] + [str(counts[role].get(s.value, 0)) for s in REPORT_STAGES]
        cells.append(str(sum(counts[role].values())))
        rows.append(_table_row(cells))
    return {"object": "block", "type": "table",
            "table": {"table_width": len(header), "has_column_header": True,
                      "children": rows}}


def build_page_blocks(pipeline: CanonicalPipeline, out_dir: str) -> list[dict]:
    stats = hygiene_stats(load_queue(out_dir))
    return [
        _heading("Snapshot (role x stage)"),
        snapshot_table_block(pipeline),
        _heading("Data hygiene"),
        _callout(f"{stats['found']} discrepancies found; {stats['resolved']} "
                 f"resolved ({stats['approved']} approved, "
                 f"{stats['dismissed']} dismissed); {stats['pending']} pending.",
                 "🧹"),
        _callout(confidence_line(stats), "🎯"),
        _callout("Generated by pipeline-auditor from synthetic data. "
                 "Nothing was auto-corrected; every fix was human-reviewed.",
                 "🤖"),
    ]


def push_report(pipeline: CanonicalPipeline, out_dir: str = "out") -> str:
    """Create the report page. Returns its URL. Raises SystemExit with a
    clear message when the env vars are missing -- fail fast, fail loud."""
    token = os.environ.get("NOTION_TOKEN")
    database_id = os.environ.get("NOTION_DATABASE_ID")
    if not token or not database_id:
        raise SystemExit(
            "--push-notion needs NOTION_TOKEN and NOTION_DATABASE_ID set "
            "(scratch workspace setup: see README). Markdown report was "
            "still written to out/report.md.")

    from notion_client import Client

    client = Client(auth=token)
    title = f"Pipeline report -- week of {pipeline.as_of.date().isoformat()}"
    page = client.pages.create(
        parent={"database_id": database_id},
        properties={"Name": {"title": _text(title)}},
        children=build_page_blocks(pipeline, out_dir),
    )
    return page.get("url", "(created; no url returned)")
